version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: "ci"
      include: "scope"
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: monthly
    commit-message:
      prefix: "ci"
      include: "scope"
  - package-ecosystem: pip
    directory: "/docs"
    schedule:
      interval: monthly
    commit-message:
      prefix: "docs"
      include: "scope"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    versioning-strategy: lockfile-only
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "feat"
      prefix-development: "chore"
      include: "scope"
